name = "metric-scheduler"
main = "src/index.js" # Menunjuk ke output build JavaScript
compatibility_date = "2024-02-22"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "crebost-production"
database_id = "23bed93f-2555c-4394-95d8-3408fd23e3e5"

# Queue Producer Binding
[[queues.producers]]
queue = "metric-harvest-queue" # Harus sama dengan nama queue yang dibuat di Cloudflare
binding = "METRIC_HARVEST_QUEUE" # Nama variabel binding di worker code (env.METRIC_HARVEST_QUEUE)

# Cron Trigger
[triggers]
# Contoh: Setiap 4 jam. Sesuaikan!
# "0 */4 * * *" = Menit 0 setiap jam ke-4 (00:00, 04:00, 08:00, 12:00, 16:00, 20:00 UTC)
# Pertimbangkan frekuensi berdasarkan jumlah postingan dan rate limit API.
# Mungkin lebih jarang jika jumlah postingan sangat banyak, atau lebih sering jika sedikit.
crons = ["15 */4 * * *"] # Menit ke-15 setiap jam ke-4, agar tidak bentrok dengan job lain di menit 0.
