name = "crebost-landing"
compatibility_date = "2024-01-15"
pages_build_output_dir = "out"

[env.production]
name = "crebost-landing"

[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_AUTH_URL = "https://crebost-auth.pages.dev"
NEXT_PUBLIC_DASHBOARD_URL = "https://crebost-dashboard.pages.dev"
NEXT_PUBLIC_ADMIN_URL = "https://crebost-admin.pages.dev"
NEXT_PUBLIC_API_URL = "https://crebost-api.pages.dev"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "11ac1ff7bee34d709cb2dd15600a17150"
