name = "payout-processor"
main = "src/index.js" # Menunjuk ke output build JavaScript
compatibility_date = "2024-02-22"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "crebost-production" # Sesuai konfigurasi Anda
database_id = "23bed93f-2555c-4394-95d8-3408fd23e3e5" # Sesuai konfigurasi Anda

# Cron Trigger
[triggers]
# Contoh: Berjalan setiap hari pukul 02:00 UTC.
# Pastikan jadwal ini memberikan cukup waktu bagi social-api-harvester dan bot-analyzer
# untuk menyelesaikan pekerjaan mereka untuk data hari sebelumnya.
crons = ["0 2 * * *"] # "At 02:00 AM every day."
