name = "bot-analyzer"
main = "src/index.js" # Menunjuk ke output build JavaScript
compatibility_date = "2024-02-22"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "crebost-production" # Sesuai konfigurasi Anda
database_id = "23bed93f-2555c-4394-95d8-3408fd23e3e5" # Sesuai konfigurasi Anda

# Cron Trigger
[triggers]
# Contoh: Berjalan setiap 6 jam, di menit ke-30 (misal, 00:30, 06:30, 12:30, 18:30 UTC)
# Jadwal ini harus dikoordinasikan agar berjalan setelah `metric-scheduler` dan `social-api-harvester`
# kemungkinan besar telah menyelesaikan siklusnya.
crons = ["30 */6 * * *"]

# [vars]
# DEFAULT_ANALYSIS_WINDOW_HOURS = "24"
# MIN_SAMPLES_FOR_THRESHOLD_CALC = "20"
